name: Continuous Delivery
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  # Only cancel in-progress if on a Pull Request
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
env:
  NODE_VERSION: 20.4.0
jobs:
  preview:
    name: Preview
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "npm"
    - name: Install dependencies
      run: npm ci
    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: powerd6/infrastructure
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  deploy:
    name: Deploy
    needs: preview
    if: ${{ github.ref == 'refs/heads/main' }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: powerd6/infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
