name: Update pulumi secret
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: The name of the secret
        required: true
      value:
        type: string
        description: The value of the secret
        required: true
      
permissions:
  contents: read
concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false
env:
  NODE_VERSION: 20.4.0
  PULUMI_STACK_NAME: powerd6/infrastructure/public
jobs:
  import:
    name: Import ${{inputs.name}}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Mask inputs
      run: |
        SECRET_VALUE=$(jq -r '.inputs.name' $GITHUB_EVENT_PATH)
        echo ::add-mask::$SECRET_VALUE
        echo ::set-output name=secret::$SECRET_VALUE
        echo SECRET_VALUE="$SECRET_VALUE" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "npm"
    - name: Install dependencies
      run: npm ci
    - name: Setup pulumi stack
      run: |-
        pulumi stack select ${{ env.PULUMI_STACK_NAME }}
        pulumi config refresh
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    - name: Import the secret
      run: pulumi config set --secret "${{ inputs.name }}" "${{ inputs.value }}"
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}


    